### PR TITLE
Remove support for "formulahendry.auto-close-tag" use in cfmleditor

### LINKED ISSUE #91: Drop support for use of formulahendry.auto-close-tag with CFMLEditor
Drop support for use of formulahendry.auto-close-tag with CFMLEditor

formulahendry.auto-close-tag could be considered unstable and can crash VSCode and / or cause high CPU usage.

"formulahendry.auto-close-tag" has been included in the unwanted extensions for some time now and I would like to be able to provide a consistent / reliable auto tag close experience.

### PR DESCRIPTION
**Pull request by ghedwards**

### CODE REVIEW

File: src/cfmlMain.ts
Comment (pixilation) [inline src/cfmlMain.ts:1]: - `getConfigurationTarget` is no longer referenced and should be removed
- `cfml.autoCloseTags.configurationTarget` is no longer referenced and should be removed
- `auto-close-tag` references can be removed from package.json and README.md

Comment (ghedwards) [reply src/cfmlMain.ts:1]: Done

File: package.json [hunk 1]
```diff
@@ -389,25 +389,10 @@
 				"cfml.autoCloseTags.enable": {
 					"order": 2,
 					"type": "boolean",
-					"markdownDescription": "Whether to enable auto-closing tags for CFML. This uses the third-party extension `auto-close-tag`. This is only checked and set on startup.",
+					"markdownDescription": "Whether to enable auto-closing tags for CFML. This is only checked and set on startup.",
```
Comment (pixilation) [inline package.json:392]: ### Suggestion

> This is only checked and set on startup

We can make the toggle work immediately:
```diff
-	const cfmlSettings: WorkspaceConfiguration = workspace.getConfiguration("cfml");
-	const enableAutoCloseTags: boolean = cfmlSettings.get<boolean>("autoCloseTags.enable", true);

-	if (enableAutoCloseTags) {
		workspace.onDidChangeTextDocument(async (event) => {
			await handleContentChanges(event);
		});
-	}
```

`handleContentChanges` already has a check for the setting, and will return early if it's not set.

File: README.md [hunk 2]
```diff
@@ -107,7 +107,7 @@ This extension contributes these settings to Visual Studio Code:
 - `cfml.definition.enable`: Whether providing definitions is enabled. [_Default_: `true`]
```
[the remark this answers is not in the document]
Comment (ghedwards) [reply README.md:107]: no idea, probably by mistake, will have a look.

**Review by pixilation — APPROVED** [review]
There's just some old text to remove and this is done
